Skip to next loop of checking if we can't source the APKBUILD

diff --git a/apkbuild-lint b/apkbuild-lint
--- a/apkbuild-lint
+++ b/apkbuild-lint
@@ -220,7 +220,10 @@ for apkbuild; do
 	if [ -f "$apkbuild" ]; then
 
 	# Source apkbuild, we need some nice values
-	srcdir="" . "$apkbuild"
+	srcdir="" . "$apkbuild" || {
+		echo "Failed to source APKBUILD in '$apkbuild'" ;
+		continue
+	}
 	default_builddir_value &
 	_builddir_is_set &
 
diff --git a/aports-lint b/aports-lint
--- a/aports-lint
+++ b/aports-lint
@@ -192,7 +192,10 @@ for apkbuild; do
 	esac
 
 	# Source apkbuild, we need some nice values
-	srcdir="" . ./"$apkbuild" 2>/dev/null
+	srcdir="" . "$apkbuild" || {
+		echo "Failed to source APKBUILD in '$apkbuild'" ;
+		continue
+	}
 
 	if [ ! -z "$depends" ]; then
 		upper_repo_depends &
